version: '3.9'
services:
  apigateway:
    networks:
      - shared
    build: 
     context: .
     dockerfile: Dockerfile
    env_file:
      - kong-manager.env
      - spec-folder.env
    environment:
      CYPRESS_RECORD_KEY: ${CYPRESS_RECORD_KEY}
    command: sh -c '
      npx cypress run --record --spec $${FOLDER}'
    volumes:
      - ./:/e2e
      - node_modules:/e2e/node_modules
      - ./cypress/reports:/e2e/cypress/reports
    ipc: host

volumes:
  node_modules: {}

networks:
  shared:
    external: true
    name: api-gateway-tests_kong-ee-net