version: '3.9'
services:
  apigateway:
    networks:
      - shared
    image: apigateway-tests:ci
    build: 
     context: .
     dockerfile: Dockerfile
    env_file:
      - kong-manager.env
      - spec-folder.env
    environment:
      CYPRESS_RECORD_KEY: ${CYPRESS_RECORD_KEY}
    command: 
      - sh
      - -lc
      - |
        if [ -n "$CYPRESS_RECORD_KEY" ]; then
          echo "Recording to Cypress Cloud"
          exec npx cypress run --record --key "$CYPRESS_RECORD_KEY" --spec "$${FOLDER}"
        else
          echo "Local run (no CYPRESS_RECORD_KEY)"
          exec npx cypress run --spec "$${FOLDER}"
        fi
    volumes:
      - ./:/e2e
      - node_modules:/e2e/node_modules
      - ./cypress/reports:/e2e/cypress/reports
    ipc: host

volumes:
  node_modules: {}

networks:
  shared:
    external: true
    name: api-gateway-tests_kong-ee-net